import '@/styles/globals.css'
import '@/styles/index.scss'
import type { AppProps } from 'next/app'
import { NextPage } from 'next'
import Head from 'next/head'
import type { ReactElement, ReactNode } from 'react'

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
}


export default function App({ Component, pageProps }: AppPropsWithLayout) {

  const getLayout = Component.getLayout ?? ((page) => page)

  return (
    <>
      <Head>
        <title>Lendsqr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png"/>
      </Head>

      <div>
        {getLayout(<Component {...pageProps} />)}
      </div>
    </>
  )
}
