import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Leadsqr | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <h1>Login Page</h1>
      </main>
    </>
  )
}

Home.getLayout = function HomePage(login: any) {
  <>
    <Layout>
      {login}
    </Layout>
  </>
}